### ISSUE TITLE
Rename project to avoid confusion with recursion schemes

### ISSUE THREAD

**Issue by andyscott** [higherkindness/catamorph#7]
Catamorph included, we have three projects that can be confused for recursion scheme projects:
- Mu (not a recursion scheme project, but Mu is used as fixed point type in recursion schemes)
- Catamorph (not a recursion scheme project, but a catamorphism is a recursion scheme for a basic structured fold)
- Droste (this is actually supposed to be about recursion schemes 😄)

I'd like to avoid confusion with the Higher Kindness projects, so I'd suggest we rename this project to "compendium", which means _"a collection of concise but detailed information about a particular subject, especially in a book or other publication."_

**Comment by pepegar** [comment]
Mu being a greek letter, it's hard to only associate it with recursion schemes.  It's mu for the _micro_ microservices, so I think we shouldn't change that one.

Regarding catamorph, I liked the name, and the idea of having a bunch of *morph projects, but I have received the complaint from enough people already, I agree in changing the name.

I like compendium as well :)

**Comment by andyscott** [comment]
The naming for the Mu project is very reasonable. I just wanted to point out that it _does have_ a recursion scheme connotation.

**Comment by juanpedromoreno** [comment]
+1 compendium

**Comment by andyscott** [comment]
I'm going to go ahead and rename the repo!
